### PR TITLE
Metrolist CI

### PR DESCRIPTION
**Pull request by hguiney**
Attempting to get Acquia to recognize the metrolist_ci branch

### CODE REVIEW

**Comment by davidrkupton** [comment]
Guys dont merge this to develop yet

**Comment by davidrkupton** [comment]
I am not sure you are intending to merge this - I think it may have been created unnecessarily.
I have deleted it so it does not get merged into Develop for now.  

We should review before a merge occurs into develop because it is active at the moment.

**Comment by davidrkupton** [comment]
The branch is still there and should be building onto `dev2` I think.

**Comment by hguiney** [comment]
@davidrkupton Correct, had no intention of merging. @mmcgowanBOS suggested creating this PR in order to populate the Code Switch dropdown list in Acquia. Should have deleted it myself afterward; apologies for the confusion.

**Pull request closed without merging**
